# Generated by Django 2.2 on 2019-05-03 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=50)),
                ('friend_mobile', models.CharField(max_length=13)),
                ('friend_group', models.CharField(choices=[('Agroup', 'A-Group'), ('Bgroup', 'B-Group'), ('Cgroup', 'C-Group'), ('Dgroup', 'D-Group')], default='Bgroup', max_length=10)),
                ('friend_relation', models.CharField(choices=[('Friend', 'Friend'), ('Business', 'Business'), ('Family', 'Family')], default='Business', max_length=10)),
                ('friend_memo', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('comment_contents', models.CharField(max_length=300)),
                ('comment_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='friends.Friends')),
            ],
            options={
                'ordering': ['-comment_created'],
            },
        ),
    ]
