# Generated by Django 2.2 on 2019-05-08 11:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='created',
        ),
        migrations.AddField(
            model_name='friends',
            name='latest_connect',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='friends',
            name='scheduled_connect',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friends',
            name='friend_relation',
            field=models.CharField(choices=[('Friend', 'Friend'), ('Business', 'Business'), ('Family', 'Family'), ('Another', 'Another')], default='Business', max_length=10),
        ),
    ]
