# Generated by Django 2.2 on 2019-05-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20190508_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_writer',
        ),
    ]
