# Generated by Django 2.2 on 2019-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_remove_comment_comment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
