# Generated by Django 2.2 on 2019-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_auto_20190527_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
