# Generated by Django 2.2 on 2019-05-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_auto_20190528_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend_mobile',
            field=models.CharField(default='010-0000-0000', max_length=13),
        ),
    ]
